const express = require('express');
const router = express.Router();
const loginController = require('../controllers/login-controller');
const registerController = require('../controllers/register-controller');
const profileController = require('../controllers/profile-controller');
router.get('/login', loginController.login);
router.get('/register', registerController.register);
router.post('/register', registerController.postRegister);
router.get('/profile', profileController);
module.exports = router;